document.querySelector("#year").textContent = new Date().getFullYear();
let today = new Date();
let options = { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' };
document.getElementById("current").innerHTML = today.toLocaleDateString('en-GB', options);
/*let a = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
let b = ['January','February','March','April','May','June','July','August','September','October','November','December'];
let day = today.getDay() + 1;
let date = today.getDate();
let month = today.getMonth() + 1;
let year = today.getFullYear();
let b = `${day}, ${date} ${month} ${year}`;
document.querySelector("#current").innerHTML = b;*/
